Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "Zaphod"
    config.disksize.size = "60GB"
    config.vm.network "public_network", bridge: "wlp9s0"
    config.vm.provision "shell", path: "install.sh"
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
        v.name = "Zaphod"
    end
end
